version: 2.1

jobs:
  test:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run:
          name: install package
          command: yarn install
      - run:
          name: run test
          command: yarn test
  build:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run:
          name: install package
          command: yarn install
      - run:
          name: install gatsby-cli
          command: yarn global add gatsby-cli
      - run:
          name: run build
          command: gatsby build

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test