version: 2.1

jobs:
  test:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run:
          name: install package
          command: yarn install
      - run:
          name: run test
          command: yarn test
  build_and_deploy:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run:
          name: install package
          command: yarn install
      - run:
          name: install gatsby-cli and netlify-cli
          command: yarn global add gatsby-cli netlify-cli
      - run:
          name: run build
          command: gatsby build
      - run:
          name: deploy
          command: netlify deploy --prod --dir public --message "site deployed from $CIRCLE_BUILD_NUM" --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build_and_deploy:
          context: Netlify
          requires:
            - test